import type { Metadata } from "next";
import "./../globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { auth } from "@clerk/nextjs/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();

  return (
    <>
      <Navbar userId={userId} />
      {children}
      <Footer />
    </>
  );
}
